import XCTest
import AppKit
@testable import NeuraBar

// Coverage for the 2026 hardening pass: clipboard privacy, power-aware
// polling cadence, Pomodoro correctness, automation safety, image-attachment
// validation, and off-main persistence.

// MARK: - Clipboard privacy + cadence

final class ClipboardPrivacyTests: XCTestCase {

    func testConcealedTypeIsSkipped() {
        // Password managers / Keychain mark secrets with ConcealedType.
        let types: [NSPasteboard.PasteboardType] = [
            .string, .init("org.nspasteboard.ConcealedType")
        ]
        XCTAssertTrue(ClipboardManager.shouldSkip(types: types),
                      "Concealed (password) pasteboard items must never be captured")
    }

    func testTransientAndSensitiveTypesAreSkipped() {
        XCTAssertTrue(ClipboardManager.shouldSkip(types: [.init("org.nspasteboard.TransientType")]))
        XCTAssertTrue(ClipboardManager.shouldSkip(types: [.init("org.nspasteboard.AutoGeneratedType")]))
        XCTAssertTrue(ClipboardManager.shouldSkip(types: [.init("com.apple.is-sensitive")]))
    }

    func testPlainTextIsNotSkipped() {
        XCTAssertFalse(ClipboardManager.shouldSkip(types: [.string]))
        XCTAssertFalse(ClipboardManager.shouldSkip(types: nil))
    }

    func testLowPowerBacksOffPolling() {
        XCTAssertGreaterThan(
            ClipboardManager.pollInterval(lowPower: true),
            ClipboardManager.pollInterval(lowPower: false),
            "Low Power Mode should stretch the clipboard poll interval"
        )
    }
}

// MARK: - System sampling cadence

final class SystemSamplingTests: XCTestCase {

    func testHiddenSamplesSlowerThanVisible() {
        let visible = SystemMonitor.sampleInterval(active: true)
        let hidden = SystemMonitor.sampleInterval(active: false)
        XCTAssertGreaterThan(hidden, visible,
                             "Hidden cadence must be slower to let the process nap")
        XCTAssertEqual(visible, 3.0, accuracy: 0.001)
    }
}

// MARK: - Pomodoro correctness

final class PomodoroHardeningTests: NBTestCase {

    func testSkipDoesNotRecordCompletedSession() {
        let p = PomodoroTimer()
        p.startFocus()
        p.skip()
        XCTAssertTrue(p.sessions.isEmpty,
                      "Skip abandons a phase — it must not count as a completed session")
        XCTAssertEqual(p.sessionsCompleted, 0)
        p.pause()
    }

    func testExtendWhileIdleIsNoOp() {
        let p = PomodoroTimer()
        let before = p.remaining
        p.extend(minutes: 5)
        XCTAssertEqual(p.remaining, before,
                       "extend() must be a no-op while idle so it can't inflate the next phase")
    }

    func testProgressIsFiniteWithZeroCustomFocus() {
        let p = PomodoroTimer()
        p.customFocusMinutes = 0
        p.mode = .custom
        XCTAssertFalse(p.progress.isNaN, "progress must never be NaN")
        XCTAssertGreaterThanOrEqual(p.progress, 0)
        XCTAssertLessThanOrEqual(p.progress, 1)
    }

    func testProgressClampedAfterExtendBeyondTotal() {
        let p = PomodoroTimer()
        p.startFocus()
        p.extend(minutes: 60) // remaining now exceeds the phase total
        XCTAssertGreaterThanOrEqual(p.progress, 0)
        XCTAssertLessThanOrEqual(p.progress, 1)
        p.pause()
    }
}

// MARK: - Automation safety

final class AutomationSafetyTests: XCTestCase {

    func testDestructiveAutomationsRequireApproval() {
        for id in ["trash", "dsstore", "derived", "lock", "sleep"] {
            XCTAssertTrue(AutomationCatalog.destructiveIDs.contains(id),
                          "\(id) is destructive/disruptive and must require confirmation")
        }
    }

    func testSafeAutomationsDoNotRequireApproval() {
        for id in ["screenshots", "sortDL", "heic", "bigFiles", "oldDL", "dmg", "hidden"] {
            XCTAssertFalse(AutomationCatalog.destructiveIDs.contains(id),
                           "\(id) should run without a confirmation prompt")
        }
    }

    func testEveryDestructiveIDExistsInCatalog() {
        let catalogIDs = Set(AutomationCatalog.all.map { $0.id })
        for id in AutomationCatalog.destructiveIDs {
            XCTAssertTrue(catalogIDs.contains(id), "destructive id \(id) has no catalog entry")
        }
    }

    func testParseCounterTrimsWhitespacePaddedValues() {
        XCTAssertEqual(parseCounter("__MOVED: 42", key: "__MOVED"), 42)
        XCTAssertEqual(parseCounter("__MOVED:7", key: "__MOVED"), 7)
    }
}

// MARK: - Note image attachment validation

final class NoteAttachmentsHardeningTests: NBTestCase {

    func testStoreRejectsNonImageData() {
        let junk = "definitely not an image".data(using: .utf8)!
        XCTAssertNil(NoteAttachments.store(data: junk),
                     "Arbitrary data must be rejected, not stored as a fake .png")
    }

    func testImageExtensionDetectsRealPNG() {
        XCTAssertEqual(NoteAttachments.imageExtension(for: Self.makePNG()), "png")
    }

    func testImageExtensionNilForJunk() {
        XCTAssertNil(NoteAttachments.imageExtension(for: Data([0, 1, 2, 3, 4, 5])))
    }

    func testPruneKeepsImageReferencedByAbsolutePathToken() throws {
        let ref = NoteAttachments.store(data: Self.makePNG())!
        let bareName = NoteAttachments.extractTokens(from: ref).first!
        // Reference the same file via an ABSOLUTE-PATH token (a body can carry
        // those) — the orphan pruner must normalize and NOT delete it.
        let absoluteToken = NoteAttachments.baseDir.appendingPathComponent(bareName).path
        let removed = NoteAttachments.pruneOrphans(referencedTokens: [absoluteToken])
        XCTAssertEqual(removed, 0, "A still-referenced image must not be deleted as an orphan")
        XCTAssertNotNil(NoteAttachments.resolve(token: bareName))
    }

    private static func makePNG() -> Data {
        let image = NSImage(size: NSSize(width: 3, height: 3))
        image.lockFocus()
        NSColor.systemBlue.drawSwatch(in: NSRect(x: 0, y: 0, width: 3, height: 3))
        image.unlockFocus()
        let tiff = image.tiffRepresentation!
        return NSBitmapImageRep(data: tiff)!.representation(using: .png, properties: [:])!
    }
}

// MARK: - Off-main persistence

final class PersistenceAsyncTests: NBTestCase {

    func testSaveAsyncRoundTrips() {
        struct Payload: Codable, Equatable { var x: Int; var name: String }
        let exp = expectation(description: "async save lands on disk")
        let original = Payload(x: 99, name: "async")
        Persistence.saveAsync(original, to: "async-test.json")
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
            XCTAssertEqual(Persistence.load(Payload.self, from: "async-test.json"), original)
            exp.fulfill()
        }
        wait(for: [exp], timeout: 3)
    }
}
